# 公共配置，所有的启用dev模式的都进行读取
spring:
  datasource:
    oracle:
      type: com.alibaba.druid.pool.DruidDataSource
      username: cloud
      password: cloud
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@127.0.0.1:49163/EE.oracle.docker

  # 配置redis
  redis:
    host: 127.0.0.1
    database: 3
    port: 6400

# 开发时配置心跳时间为10秒以及告诉server端10秒种剔除
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 10
