spring:
  cloud:
    gateway:
      routes:
      - id: cloud-sys-web
        uri: lb://cloud-sys-web
        predicates:
          - Path=/api/sysweb/**
        filters:
          - StripPrefix=2
      - id: cloud-auth-server
          uri: lb://cloud-auth-server
          predicates:
            - Path=/api/authserver/**
          filters:
            - StripPrefix=2
      discovery:
        locator:
          enabled: true