create table ROLE_PERMISSION_RELATION
(
    ROLEID NUMBER not null
        constraint ROLE_PER_SYS_ROLEID_FK
            references SYS_ROLE,
    PID    NUMBER not null
        constraint ROLE_PE_SYS_PER_PID_FK
            references SYS_PERMESSION,
    constraint ROLE_PERMISSION_RELATION_PK
        primary key (ROLEID, PID)
)
/

INSERT INTO CLOUD.ROLE_PERMISSION_RELATION (ROLEID, PID) VALUES (1, 1);
INSERT INTO CLOUD.ROLE_PERMISSION_RELATION (ROLEID, PID) VALUES (1, 2);
INSERT INTO CLOUD.ROLE_PERMISSION_RELATION (ROLEID, PID) VALUES (2, 1);
INSERT INTO CLOUD.ROLE_PERMISSION_RELATION (ROLEID, PID) VALUES (2, 3);